name: Publish to Jitpack.io

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Jitpack
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Version
        id: setup
        run: |
          echo "TAG VERSION: ${{ github.ref_name }}"
          echo "RELEASE VERSION: ${GITHUB_REF_NAME#v}"
          echo "::set-output name=release_name::${GITHUB_REF_NAME#v}"
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Fetch Jitpack IO Library
        uses: wei/curl@master
        continue-on-error: true
        with:
          args: --verbose https://jitpack.io/com/github/fadlurahmanfdev/kotlin_local_storage/${{ github.ref_name }}/kotlin_local_storage-${{ github.ref_name }}.pom
          
